services:
  - type: web
    name: eye-in-the-sky-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: AZURE_ENDPOINT
        sync: false
      - key: AZURE_API_KEY
        sync: false
